config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'signup', to: 'users#new'
  resources :petitions do
    member do
      put "support", to: "petitions#support"
      put "unsupport", to: "petitions#unsupport"
  end
end
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/petition.rb
class Petition < ApplicationRecord
  include AASM
  VOUTE_SIZE = 100

  belongs_to :user
  acts_as_votable

  validates :title, presence: true, length: { minimum: 4, maximum: 255 }
  validates :description, presence: true, length: { minimum: 1, maximum: 10000 }
  validates :user_id, presence: true

  after_commit :check_voute_size

  aasm column: 'state' do
    state :vouting, initial: true
    state :declined
    state :complited
    state :waiting

    event :complite do
      transitions from: :waiting, to: :complited
    end
    event :wait do
      transitions from: :vouting, to: :waiting
    end
    event :decline do
      transitions from: :vouting, to: :declined
    end

  end

  private

  def check_voute_size
    wait! if (get_upvotes.size >= VOUTE_SIZE && !waiting?)
  end
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: true,uniqueness: { case_sensitive: false },
 format: { with: VALID_EMAIL_REGEX }
  validates :first_name, presence: true
  validates :second_name, presence: true
  validates :city, presence: true
  validates :passport_number, presence: true, uniqueness:true, length: {is:8}
  validates :phone_number, presence: true
  validates :date_of_birth, presence:true
  has_many :petitions

  before_save { self.email = email.downcase }
  has_secure_password
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  def logged_in?
      !!current_user
  end
  def require_user
    if !logged_in?
    flash[:danger] = "You must be logged in to perform that action"
    redirect_to root_path
   end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @petitions=Petition.all
    end
end

app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  before_action :set_article, only: [:show, :destroy,:support,:unsupport]

    def index
      @petitions=Petition.all
      @petitions = Petition.paginate(page: params[:page], per_page: 5)
    end
    def new
      @petition = Petition.new
    end

      def create
        @petition = Petition.new(petition_params)
        if @petition.save
         flash[:success] = "Petition was successfully created"
         redirect_to petition_path(@petition)
        else
         render 'new'
        end
      end
      def show

     end
     def destroy
        @petition.destroy
        flash[:warning] = "Petition was deleted"
        redirect_to petitions_path
     end

     def support
       @petition.upvote_by current_user
       redirect_to petition_path
     end

     def unsupport
       @petition.downvote_by current_user
       redirect_to petition_path
     end

    private
      def petition_params
       params.require(:petition).permit(:title, :description,:user_id)
      end
      def set_article
        @petition = Petition.find(params[:id])
       end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

 end
def create
  user = User.find_by(email: params[:session][:email].downcase)
  if user  && user.authenticate(params[:session][:password])
   session[:user_id] = user.id
   flash[:success] = "You have logged in"
   redirect_to petitions_path
  else
   flash.now[:danger] = "There was something wrong with your login information"
   render 'new'
  end
 end
def destroy
  session[:user_id] = nil
  flash[:success] = "You have logged out"
  redirect_to root_path
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
      if @user.save
        flash[:success] = "Welcome to the alpha servise #{@user.username}"
        redirect_to root_path
      else
        render 'new'
      end
  end
  def edit
    @user = User.find(params[:id])
  end

  def show
    
  end

private
  def user_params
    params.require(:user).permit(:username, :email, :password,:first_name,:second_name,:city,:passport_number,:phone_number,:date_of_birth)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/petitions_helper.rb
module PetitionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="<% if current_page?('/') %> transparent-footer<% end %>">
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= link_to 'Petition-online', root_path, :class=>"navbar-brand"%>
    </div>
    <div class="col-md-3 offset-md-6">
      <a class="navbar-brando" href="https://t.me/AOleinik">Made by Oleksandr Oliinyk</a>
    </div>
  </div>
</div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar shadow-sm fixed-top navbar-light navbar-expand-lg <% if current_page?('/') %> transparent<% else %> "style="background-color: #e3f2fd; <% end %>" role="navigation">
  <%= link_to 'Petition-online', root_path, :class=>"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav d-flex w-100">
      <li class="nav-item active ">
        <%= link_to 'List', petitions_path, :class=>'nav-link '%>
      </li>
      <li class="nav-item mr-auto">
        <% if logged_in? %>
          <%= link_to 'New petition', new_petition_path, :class=>'nav-link '%>
        <% else %>
          <%= link_to 'New petition', new_petition_path, :class=>'nav-link disabled'%>
        <% end %>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to 'User', current_user, :class=>'nav-link ' %>
        </li>
      <% end %>
      <li class="nav-item">
        <% if !logged_in? %>
          <%= link_to 'Log in', login_path, :class=>'nav-link ' %>
        <% else %>
          <%= link_to 'Log out', logout_path, method: :delete , :class=>'nav-link '%>
        <% end %>
      </li>
      <% if !logged_in? %>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, :class=>'nav-link ' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetitionOnline</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrap <% if current_page?('/')%> main <% end %>">
      <%= render 'layouts/navigation' %>
      <div class="container">
        <%= render 'shared/messages' %>
            <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="welcome text-center">
  <h1>Welcome to PetitionOnline</h1>
  <h2>Start a petition, build support, win campaigns or simply follow the causes you love.</h2>
  
</div>

app/views/petitions/index.html.erb
<div class="page-header">

<h1>Listing all petitions</h1>
</div>
<% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
<div class="row">
  <% @petitions.each do |petition| %>
<div class="col-md-12">
  <div class="petition-card petition-card-<%= petition.state%>">
    <div class="petition-card__header d-flex justify-content-between">
      <div class="petition-card__header__id">
        Petition number: #<%= petition.id%>
      </div>
      <p class="petition-card__header__status">Status: <%= petition.state %></p>
    </div>
    <div class="petition-card__title">
      <%= petition.title %>
    </div>
    <div class="petition-card__description">
      <%= petition.description %>
    </div>
    <div class="petition-card__actions mt-2">
      <%= link_to 'View more..', petition_path(petition), :class=>"btn btn-outline-info" %>
    </div>


  </div>
</div>
  <% end %>

</div>
<div class="row">
  <div class="mx-auto">
      <%= will_paginate @petitions,renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>

</div>

app/views/petitions/new.html.erb
<h1>Create an petition</h1>
<%= render 'shared/errors', obj: @petition %>
<div class="row">
 <div class="col-12">
<%= form_for(@petition,:html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
 <div class="control-label col-12">
    <%= f.label :title %><br>
    </div>
    <div class="col-12">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-12">
      <%= f.label :Organisation %><br>
      </div>
      <div class="col-12">
      <%= f.text_field :title, class: "form-control", placeholder: "Organisation", autofocus: true %>
     </div>
    </div>
  <div class="form-group">
    <div class="control-label col-12">
     <%= f.label :description %>
    </div>
    <div class="col-12">
     <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
    </div>
   </div>
   <div class="form-group">
    <div class="offset-10 col-2">
     <%= f.submit class: 'btn btn-primary btn-large' %>
    </div>
   </div>
       User ID:<%= current_user.id %> <br>
       User Name: <%= current_user.username %>
       <%= f.hidden_field :user_id, value: current_user.id%>
   <% end %>

<%= link_to 'Back', petitions_path %>
 </div>
</div>

app/views/petitions/show.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
<p class="petition-status">Status: <%= @petition.state %></p>
<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: <%= @petition.get_upvotes.size.to_f %>%;" aria-valuenow="<%= @petition.get_upvotes.size%>" aria-valuemin="0" aria-valuemax="100"><%= @petition.get_upvotes.size%>/100</div>
</div>
<h2><%= @petition.title %></h2>

<hr>
<div class="petition__info">
  <div class="row h-100">
    <div class="col-2 d-flex justify-content-between flex-column h-100">
      <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-description" role="tab" aria-controls="description" aria-selected="true">Text of petition</a>
        <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-subscribers" role="tab" aria-controls="v-pills-profile" aria-selected="false">Subscribers</a>
        <%  if @petition.state == "complited"  %>
          <a class="nav-link " id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-answer" role="tab" aria-controls="v-pills-messages" aria-selected="false">Answer</a>
        <% else %>
          <a class="nav-link disabled" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-answer" role="tab" aria-controls="v-pills-messages" aria-selected="false">Answer</a>
        <% end %>
      </div>
      <div class="petition-actions">
        <% if @petition.state == "vouting" %>
          <% if logged_in? %>
            <% if current_user.voted_up_on? @petition %>
              <%= link_to unsupport_petition_path(@petition),:class=>"btn btn-warning", method: :put do %>
                Unsupport
              <% end %>
            <% else %>
              <%= link_to support_petition_path(@petition),:class=>"btn btn-success", method: :put do %>
                Support
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-10">
      <div class="tab-content" id="v-pills-tabContent">
        <div class="tab-pane fade show active" id="v-pills-description" role="tabpanel" aria-labelledby="v-pills-home-tab"><%= @petition.description %></div>
        <div class="tab-pane fade" id="v-pills-subscribers" role="tabpanel" aria-labelledby="v-pills-profile-tab">
          <p>User supported this petition: <%= @petition.get_upvotes.size %> from 1500</p>
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th scope="col">#</th>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
              </tr>
            </thead>
            <tbody>
              <% @petition.votes_for.up.by_type(User).voters.each do |user| %>
              <tr>
                <th scope="row"><%= user.id %></th>
                <td><%= user.first_name %></td>
                <td><%= user.second_name %></td>
              </tr>
              <% end%>
              </tbody>
          </table>
        </div>
        <div class="tab-pane fade" id="v-pills-answer" role="tabpanel" aria-labelledby="v-pills-messages-tab">...</div>
      </div>
    </div>
  </div>
</div>
<hr>
<%= link_to "Show all petitions", petitions_path, class: "btn btn-xs btn-success"  %>
<% if logged_in? %>
  <% if @petition.user_id == current_user.id %>
    <%= link_to "Delete", petition_path(@petition), method: :delete, data: { confirm: "Are you sure you want to delete this petition?"}, class: "btn btn-xs btn-danger" %>
  <% end %>
<% end %>
<small>Created by: <%= @petition.user.first_name if @petition.user %> <%= @petition.user.second_name if @petition.user %>,
<%= (@petition.updated_at).strftime("Published: %d:%m:%Y at %H:%M") %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
 <div class="row">
  <div class="col-8 offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this article from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <%= obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-12 ">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/users/new.html.erb
<h1>Registration new user</h1>
<%= render 'shared/errors', obj: @user %>
<div class="row">
 <div class="col-12">
<%= form_for(@user,:html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
 <div class="control-label col-sm-2">
    <%= f.label :username %><br>
    </div>
    <div class="col-6">
    <%= f.text_field :username, class: "form-control", placeholder: "Your username", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-2">
      <%= f.label :email %><br>
      </div>
      <div class="col-6">
      <%= f.text_field :email, class: "form-control", placeholder: "example@mail.com", autofocus: true %>
     </div>
    </div>
    <div class="form-group">
     <div class="control-label col-2">
        <%= f.label :first_name %><br>
        </div>
        <div class="col-6">
        <%= f.text_field :first_name, class: "form-control", placeholder: "Your first name", autofocus: true %>
       </div>
      </div>
      <div class="form-group">
       <div class="control-label col-2">
          <%= f.label :second_name %><br>
          </div>
          <div class="col-6">
          <%= f.text_field :second_name, class: "form-control", placeholder: "Your second name", autofocus: true %>
         </div>
        </div>
        <div class="form-group">
        <div class="control-label col-2">
           <%= f.label :password %><br>
           </div>
           <div class="col-6">
           <%= f.password_field :password, class: "form-control", placeholder: "Your first name", autofocus: true %>
          </div>
         </div>

        <div class="form-group">
         <div class="control-label col-2">
            <%= f.label :city %><br>
            </div>
            <div class="col-6">
            <%= f.text_field :city, class: "form-control", placeholder: "Your city", autofocus: true %>
           </div>
          </div>
          <div class="form-group">
           <div class="control-label col-2">
              <%= f.label :passport_number %><br>
              </div>
              <div class="col-6">
              <%= f.text_field :passport_number, class: "form-control", placeholder: "Your passport", autofocus: true %>
             </div>
            </div>
            <div class="form-group">
             <div class="control-label col-2">
                <%= f.label :phone_number %><br>
                </div>
                <div class="col-6">
                <%= f.text_field :phone_number, class: "form-control", placeholder: "Your phone number", autofocus: true %>
               </div>
              </div>
              <div class="form-group">
               <div class="control-label col-2">
                  <%= f.label :date_of_birth %><br>
                  </div>
                  <div class="col-6">
                  <%= f.date_field :date_of_birth, class: "form-control", placeholder: "Your date od birth", autofocus: true %>
                 </div>
                </div>

   <div class="form-group">
    <div class="offset-2 col-10">
     <%= f.submit class: 'btn btn-primary btn-large' %>
    </div>
   </div>
<% end %>

<%= link_to 'Back', petitions_path %>
 </div>
</div>

app/views/users/show.html.erb
<h1>User:  <%= current_user.username %></h1>

<div class="row">
  <div class="col-md-3">
    First name:
  </div>
  <div class="col-md-9">
    <%= current_user.first_name %>
  </div>
  <div class="col-md-12">
    <hr>
  </div>
  <div class="col-md-3">
    Second name:
  </div>
  <div class="col-md-9">
    <%= current_user.second_name %>
  </div>
  <div class="col-md-12">
    <hr>
  </div>
  <div class="col-md-3">
    Email:
  </div>
  <div class="col-md-9">
    <%= current_user.email %>
  </div>
  <div class="col-md-12">
    <hr>
  </div>
  <div class="col-md-3">
    Your date of birth:
  </div>
  <div class="col-md-9">
    <%= current_user.date_of_birth %>
  </div>
  <div class="col-md-12">
    <hr>
  </div>
  <div class="col-md-3">
    Passport number:
  </div>
  <div class="col-md-9">
    <%= current_user.passport_number %>
  </div>
  <div class="col-md-12">
    <hr>
  </div>
  <div class="col-md-3">
    City where are you live:
  </div>
  <div class="col-md-9">
    <%= current_user.city %>
  </div>

</div>
<hr>
<%=  (current_user.created_at).strftime("Registered: %d %B %Y at %H:%M")%>